function [fitresult, gof] = createFit(time, disp)
%CREATEFIT(TIME,DISP)
%  Create a fit.
%
%  Data for 'testfit_1' fit:
%      X Input: time
%      Y Output: disp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Apr-2025 12:41:00


%% Fit: 'testfit_1'.
[xData, yData] = prepareCurveData( time, disp );

% Set up fittype and options.
ft = fittype( 'A*exp(-zeta*omega_n*x)*cos(omega_d*x+phi)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 -0.01 0 0 -Inf 0];
opts.StartPoint = [0.05 0 6.28 6.28 0.223811939491137 0.02];
opts.Upper = [0.2 0.01 10 10 Inf 0.5];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'testfit_1' );
h = plot( fitresult, xData, yData );
legend( h, 'disp vs. time', 'testfit_1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'time', 'Interpreter', 'none' );
ylabel( 'disp', 'Interpreter', 'none' );
grid on


