function data_import = import_data(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PF00 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  PF00 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  pf00 = importfile("D:\EFDL\Old_Data\RawData\001_pf00.00hz.dat", [24, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Mar-2025 19:42:42

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [24, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["LabVIEWMeasurement", "Var2", "Var3", "Var4", "VarName5", "Var6"];
opts.SelectedVariableNames = ["LabVIEWMeasurement", "VarName5"];
opts.VariableTypes = ["double", "string", "string", "string", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var6"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var6"], "EmptyFieldRule", "auto");

% Import the data
data_import = readtable(filename, opts);

%% Convert to output type
data_import = table2array(data_import);
end