function plot_fn(results,lower_bound,upper_bound,x_num,y_num,config_idx,name,plot_legend,plotting_color,plotting_marker,errorbars)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
distance = str2double(extractBetween(name,1,3))/10;
legend_label = distance+"D";

x_data = squeeze(results{x_num}{config_idx}(:));
y_data = squeeze(results{y_num}{config_idx}(:));
lwr_bound = squeeze(lower_bound{y_num}{config_idx}(:));
up_bound = squeeze(upper_bound{y_num}{config_idx}(:));

if errorbars == 1
    errorbar(x_data,y_data,lwr_bound,up_bound,...
        plotting_marker{config_idx}, ...
        'MarkerFaceColor',plotting_color(config_idx,:), ...
        'MarkerEdgeColor','k', ...
        'DisplayName',legend_label, ...
        LineStyle='none', ...
        Color='k', ...
        MarkerSize=8)
else
    plot(x_data,y_data, ...
        plotting_marker{config_idx}, ...
        'MarkerFaceColor',plotting_color(config_idx,:), ...
        'MarkerEdgeColor','k', ...
        'DisplayName',legend_label, ...
        LineStyle='-', ...
        Color='k', ...
        MarkerSize=8)
end

xlim([0 max(squeeze(results{x_num}{config_idx}(:)))+1])

if plot_legend == 1
    legend
end

box on

end